### ISSUE TITLE
如何调用题库

### ISSUE THREAD

**Issue by muyichenfeng** [ConchBrainClub/chaoxingtopic#1]
油猴脚本的大神已经停更，是否考虑接手？这个题库如何调用

**Comment by lixinyang123** [comment]
呃。。。你好，其实我也很久没维护了。。。。今天忽然间很多人加我，我还有点懵逼😂
这个软件当初是为了刷我自己那几门课写的。。所以设计的时候很多东西都没有考虑进来，比如多选题什么的
所以问题比较多

还有就是我们这一段课比较多。。。有什么问题也没办法第一时间解决，所以还是希望多一些人一起完善一下

仓库在这里：https://github.com/ConchBrainClub/ChaoxingScript

非常感谢！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: muyichenfeng<mailto:notifications@github.com>
发送时间: 2020年4月20日 9:57
收件人: ConchBrainClub/chaoxingtopic<mailto:chaoxingtopic@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [ConchBrainClub/chaoxingtopic] 如何调用题库 (#1)


油猴脚本的大神已经停更，是否考虑接手？这个题库如何调用

**Comment by lixinyang123** [comment]
题库的话推荐直接访问网站查询，因为题库的接口并没有模糊查询功能，只能配合脚本使用
